package com.example.david.tradingapplication;

import android.app.Activity;
import android.support.annotation.NonNull;
import android.support.v4.app.Fragment;
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CompoundButton;
import android.widget.TextView;
import android.widget.ToggleButton;

import java.util.ArrayList;
import java.util.List;

public class CryptoFragment extends Fragment{
    private int page;
    private String pageTitle;

    //recyclerView variables
    RecyclerView.LayoutManager mLayoutManager;
    RecyclerView.Adapter mAdapter;
    RecyclerView rvCrypto;

    CurrencyObject currencyObject;
    List<CurrencyObject> cryptoList;


    public CryptoFragment() {
        // Required empty public constructor
    }

    public static CryptoFragment newInstance(int page, String pageTitle) {
        CryptoFragment cryptoFragment = new CryptoFragment();
        Bundle bundle = new Bundle();
        bundle.putInt("pageNumber", page);
        bundle.putString("pageTitle", pageTitle);
        cryptoFragment.setArguments(bundle);
        return cryptoFragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        this.page = getArguments().getInt("pageNumber", 0);
        this.pageTitle = getArguments().getString("pageTitle");
    }

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_crypto_picker, container, false);

        //getting list of crypto's generated by the activity
        CurrencySelectionActivity activity = (CurrencySelectionActivity) getActivity();
        cryptoList = new ArrayList<>();
        //checking list was passes along
        if (activity != null) {
            cryptoList = activity.cryptoList;
        }

        InitalizeRecyclerViewUI(view);

        return view;
    }

    public void InitalizeRecyclerViewUI(View view) {
        rvCrypto = (RecyclerView) view.findViewById(R.id.rv_crypto_selection);

        //linear layout manager
        mLayoutManager = new LinearLayoutManager(this.getActivity());
        rvCrypto.setLayoutManager(mLayoutManager);

        //specifying the adapters
        //this passes in the list of items
        mAdapter = new RVAdapter(cryptoList);
        rvCrypto.setAdapter(mAdapter);
    }

    //toggles the currencies objects watching status in the list at position
    public void ToggleWatching(int position) {
        cryptoList.get(position).toggleWatching();
        //passing the new crypto list back to the activity that contains this fragment
        if (cryptoList.get(position).watching())
            Log.d("debugMode", "watching " + cryptoList.get(position).getName());
        else
            Log.d("debugMode", "NOT watching " + cryptoList.get(position).getName());

        CurrencySelectionActivity activity = (CurrencySelectionActivity) getActivity();
        if (activity != null) {
            activity.cryptoList = this.cryptoList;
        }
    }

    public class RVAdapter extends RecyclerView.Adapter<RVAdapter.ViewHolder> {
        List<CurrencyObject> mValues;

        //constructed used to pass in the values to display
        public RVAdapter(List<CurrencyObject> mValues) {
            this.mValues = mValues;
        }

        @NonNull
        @Override
        public RVAdapter.ViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
            View view = (View) LayoutInflater.from(parent.getContext()).inflate(R.layout.crypto_selection_row, parent, false);
            ViewHolder vh = new ViewHolder(view);
            return vh;
        }

        //replaces the contents of the view, invoked by the layout manager
        @Override
        public void onBindViewHolder(@NonNull final RVAdapter.ViewHolder holder, final int position) {
            holder.mCryptoSymbol.setText(mValues.get(position).getSymbol());
            holder.mCryptoName.setText(mValues.get(position).getName());

            holder.mWatchButton.setChecked(mValues.get(position).watching());

            holder.mWatchButton.setOnClickListener(new View.OnClickListener() {
                public void onClick(View view) {
                    //toggling the object in the main list
                    ToggleWatching(position);
                }
            });
        }

        //returns the number of items in the view
        @Override
        public int getItemCount() {
            return mValues.size();
        }

        //creates the new views, invoked by the layout manager
        class ViewHolder extends RecyclerView.ViewHolder {
            public TextView mCryptoSymbol;
            public TextView mCryptoName;
            public ToggleButton mWatchButton;

            public ViewHolder(View view) {
                super(view);
                mCryptoSymbol = view.findViewById(R.id.crypto_row_selection_symbol_tv);
                mCryptoName = view.findViewById(R.id.crypto_row_selection_name_tv);
                mWatchButton = view.findViewById(R.id.crypto_row_selection_switch);
            }
        }

    }
}
